---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  dependsOn:
    - name: cilium
      namespace: kube-system

  interval: 5m
  chart:
    spec:
      chart: metallb
      version: 0.13.5
      sourceRef:
        kind: HelmRepository
        name: metallb-charts
        namespace: flux-system
      interval: 5m
  values:
    crds:
      enabled: false
    prometheusRule:
      enabled: true
    controller:
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
    speaker:
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
      tolerations:
        - effect: "NoExecute"
          operator: "Exists"
        - effect: "NoSchedule"
          operator: "Exists"
      frr:
        enabled: false

    prometheus:
      serviceAccount: kube-prometheus-stack-prometheus
      namespace: monitoring

      podMonitor:
        enabled: true
      prometheusRule:
        enabled: true
