---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-nfs
spec:
  storageClassName: media-nfs
  capacity:
    storage: 55Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: "${TRUENAS_VM_ADDRESS}"
    path: /mnt/tank/media
#  mountOptions:
#    - nfsvers=4.2
#    - tcp
#    - intr
#    - hard
#    - noatime
#    - nconnect=8
#    - nodiratime
#    - rsize=1048576
#    - wsize=1048576
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-nfs
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: media-nfs
  resources:
    requests:
      storage: 55Ti
