---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bazarr
  namespace: media
spec:
  interval: 5m
  install:
    disableWait: true
    remediation:
      retries: 100
  upgrade:
    remediation:
      retries: 100
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: bazarr
      version: 10.6.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/bazarr
      tag: v1.1.0
    env:
      TZ: "${TZ}"

    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 100

    ingress:
      main:
        primary: true
        enabled: true
        ingressClassName: "traefik"
        annotations:
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
          external-dns.alpha.kubernetes.io/target: "${SECRET_CLOUDFLARE_TUNNEL_ID_2}.cfargotunnel.com"
        hosts:
          - host: "bazarr.${SECRET_DOMAIN_CASA}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "bazarr.${SECRET_DOMAIN_CASA}"
      local:
        enabled: true
        ingressClassName: "traefik"
        hosts:
          - host: &hostinternal "{{ .Release.Name }}.${SECRET_DOMAIN_INTERNAL}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *hostinternal

    persistence:
      config:
        enabled: true
        existingClaim: bazarr-config-v1
      media:
        enabled: true
        existingClaim: media-nfs
        mountPath: /media
      backup:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "${TRUENAS_VM_ADDRESS}"
            path: /mnt/tank/backups/softwarrself/bazarr
        mountPath: /config/backup
        readOnly: false
      sub-cleaner:
        enabled: true
        type: configMap
        name: bazarr-sub-cleaner-cm
        mountPath: /scripts
        defaultMode: 511

    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 16Gi
    prometheus:
      podMonitor:
        enabled: true
        interval: 10m
        scrapeTimeout: 2m
      volumeMounts:
        - name: config
          mountPath: /config
          readOnly: true
