---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: calibre
  namespace: media
spec:
  chart:
    spec:
      chart: app-template
      version: 0.2.1
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 15m
  values:
    image:
      repository: ghcr.io/linuxserver/calibre
      tag: 6.4.0

    podSecurityContext:
      supplementalGroups:
        - 568

    env:
      TZ: ${TZ}
      PGID: 65539

    probes:
      liveness:
        enabled: true
      readiness:
        enabled: true
      startup:
        enabled: true
        spec:
          initialDelaySeconds: 30
          timeoutSeconds: 1
          ## This means it has a maximum of 10*30=300 seconds to start up before it fails
          periodSeconds: 10
          failureThreshold: 30

    persistence:
      config:
        enabled: true
        existingClaim: calibre-config
      media:
        enabled: true
        existingClaim: media-nfs
        mountPath: /media

    service:
      main:
        ports:
          http:
            port: &port 8080

    ingress:
      main:
        primary: true
        enabled: true
        ingressClassName: "traefik"
        annotations:
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
          external-dns.alpha.kubernetes.io/target: "${SECRET_CLOUDFLARE_TUNNEL_ID_2}.cfargotunnel.com"
        hosts:
          - host: &host "calibre.${SECRET_DOMAIN_CASA}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host

    resources:
      requests:
        cpu: 0.003
        memory: 1Gi
      limits:
        memory: 10Gi
