clusterName: nanocluster
talosVersion: v1.3.2
kubernetesVersion: v1.26.0
endpoint: https://10.13.10.98:6443
allowSchedulingOnMasters: true
clusterPodNets:
  - 10.244.0.0/16
clusterSvcNets:
  - 10.96.0.0/12
cniConfig:
  name: custom
  urls:
    - https://raw.githubusercontent.com/CommReteris/talos-homelab/main/talos/cilium/quick-install.yaml
nodes:
  - hostname: nano-0
    ipAddress: 10.13.10.190
    controlPlane: true
    installDisk: /dev/sda
    install:
      bootloader: true
      wipe: true
    nameservers:
      - 10.13.10.2
    networkInterfaces:
      - interface: eth0
        mtu: 1498
        vip:
          ip: 10.13.10.98
        dhcp: true
    configPatches:
      - op: add
        path: /cluster/apiServer/certSANs
        value:
          - 10.13.10.98
          - nano-0
          - nano-0.rengo.internal
          - nanocluster.rengo.internal
  - hostname: nano-1
    ipAddress: 10.13.10.191
    controlPlane: true
    installDisk: /dev/sda
    install:
      bootloader: true
      wipe: true
    nameservers:
      - 10.13.10.2
    networkInterfaces:
      - interface: eth0
        mtu: 1498
        dhcp: true
        vip:
          ip: 10.13.10.98
    configPatches:
      - op: add
        path: /cluster/apiServer/certSANs
        value:
          - 10.13.10.98
          - nano-1
          - nano-1.rengo.internal
          - nanocluster.rengo.internal
  - hostname: nano-2
    ipAddress: 10.13.10.202
    controlPlane: true
    installDisk: /dev/sda
    install:
      bootloader: true
      wipe: true
    nameservers:
      - 10.13.10.2
    networkInterfaces:
      - interface: eth0
        mtu: 1498
        dhcp: true
        vip:
          ip: 10.13.10.98
    configPatches:
      - op: add
        path: /cluster/apiServer/certSANs
        value:
          - 10.13.10.98
          - nano-2
          - nano-2.rengo.internal
          - nanocluster.rengo.internal
  - hostname: nano-3
    ipAddress: 10.13.10.210
    controlPlane: false
    installDisk: /dev/sda
    install:
      bootloader: true
      wipe: true
    inlinePatch:
      machine:
        time:
          servers:
            - time.cloudflare.com
        network:
          interfaces:
            - interface: eth0
              mtu: 1498
              dhcp: true

controlPlane:
  configPatches:
    - op: add
      path: /machine/kubelet/extraArgs
      value:
        feature-gates: GracefulNodeShutdown=true,MixedProtocolLBService=true,EphemeralContainers=true,ServerSideApply=true
        # rotate-server-certificates: "true"
    - op: add
      path: /machine/install/extraKernelArgs
      value:
        - talos.logging.kernel=udp://10.45.0.2:6050/
  inlinePatch:
    cluster:
      apiServer:
        disablePodSecurityPolicy: true
        admissionControl: []
        certSANs:
          - nanocluster.rengo.internal
        extraArgs:
          feature-gates: MixedProtocolLBService=true,EphemeralContainers=True
      controllerManager:
        extraArgs:
          feature-gates: MixedProtocolLBService=true,EphemeralContainers=True
      proxy:
        disabled: true
      discovery:
        enabled: true
        registries:
          kubernetes: {}
          service:
            disabled: true
      etcd:
        extraArgs:
          election-timeout: "5000"
        subnet: 10.13.10.0/24
      # extraManifests:
      #   - https://raw.githubusercontent.com/alex1989hu/kubelet-serving-cert-approver/main/deploy/standalone-install.yaml
      #   - https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml
    machine:
      kubelet:
        nodeIP:
          validSubnets:
            - 10.13.10.0/24
        extraArgs:
          feature-gates: GracefulNodeShutdown=true,MixedProtocolLBService=true,EphemeralContainers=true,ServerSideApply=true
          # rotate-server-certificates: "true"
      time:
        disabled: false
        servers:
          - time.cloudfare.com
worker:
  configPatches:
    - op: add
      path: /machine/kubelet/extraArgs
      value:
        feature-gates: GracefulNodeShutdown=true,MixedProtocolLBService=true,EphemeralContainers=true,ServerSideApply=true
        # rotate-server-certificates: "true"
  inlinePatch:
    machine:
      kubelet:
        nodeIP:
          validSubnets:
            - 10.13.10.0/24
      time:
        disabled: false
        servers:
          - time.cloudfare.com
