---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: k8s-gateway
  namespace: networking
spec:
  interval: 10m
  chart:
    spec:
      chart: k8s-gateway
      version: 1.1.11
      sourceRef:
        kind: HelmRepository
        name: k8s-gateway-charts
        namespace: flux-system
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    nameOverride: k8s-gateway
    domain: "${SECRET_DOMAIN_INTERNAL}"
    ttl: 1
    service:
      type: LoadBalancer
      port: 53
      loadBalancerIP: "${SVC_K8S_GATEWAY_ADDR}"
      externalTrafficPolicy: Local
    resources:
      requests:
        memory: 100Mi
        cpu: 25m
      limits:
        memory: 250Mi
