---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: loki
      version: 3.2.1
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: flux-system
      interval: 5m
  values:
    loki:
      structuredConfig:
        auth_enabled: false

      server:
        http_listen_port: 3100

      ingester:
        lifecycler:
          address: 127.0.0.1
          ring:
            kvstore:
              store: inmemory
            replication_factor: 1
          final_sleep: 0s
        chunk_idle_period: 5m
        chunk_retain_period: 30s

      schema_config:
        configs:
          - from: 2020-05-15
            store: boltdb
            object_store: filesystem
            schema: v11
            index:
              prefix: index_
              period: 168h

      storage_config:
        boltdb:
          directory: /tmp/loki/index

        filesystem:
          directory: /tmp/loki/chunks

      limits_config:
        enforce_metric_name: false
        reject_old_samples: true
        reject_old_samples_max_age: 168h
      gateway:
        enabled: true
        replicas: 3
        ingress:
          enabled: true
          ingressClassName: "traefik"
          hosts:
            - host: &host "loki.${SECRET_DOMAIN_INTERNAL}"
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - hosts:
                - *host
      write:
        replicas: 3
        persistence:
          size: 10Gi
          accessMode: ReadWriteOnce
          storageClass: rook-ceph-block
      read:
        replicas: 3
        extraVolumeMounts:
          - name: loki-rules
            mountPath: /rules/fake
          - name: loki-rules-tmp
            mountPath: /tmp/scratch
          - name: loki-tmp
            mountPath: /tmp/loki-tmp
        extraVolumes:
          - name: loki-rules
            configMap:
              name: loki-alerting-rules
          - name: loki-rules-tmp
            emptyDir: { }
          - name: loki-tmp
            emptyDir: { }
        persistence:
          size: 10Gi
          accessMode: ReadWriteOnce
          storageClass: rook-ceph-block
      monitoring:
        selfMonitoring:
          enabled: false
          grafanaAgent:
            installOperator: false
