apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: loki-secrets
    namespace: monitoring
stringData:
    S3_BUCKET_NAME: ENC[AES256_GCM,data:MV+YRw==,iv:tnN+xeI2ubhIgWQFvKZgcpt3DtNnkuIdYtzw6phaYts=,tag:837jQPowmx/gbdWyuhsg/A==,type:str]
    S3_BUCKET_HOST: ENC[AES256_GCM,data:gPY8J1KxHqffloQ5HQ==,iv:HmK/74NMjvMvJqfyC+J9Ibb5bqzHHAK1jWRj/zjgYlI=,tag:4/IenwnDKgA9dmYcZUfxwg==,type:str]
    S3_BUCKET_REGION: ""
    S3_ACCESS_KEY: ENC[AES256_GCM,data:JypQHT6/WpUmyXFIcxvvaHCCQmo=,iv:qqb2D+31TT7yu1maWLmeOv2506mUoGKBVFmyZSDYYF4=,tag:spqZyGo39rbe3VlJkDBO1Q==,type:str]
    S3_SECRET_KEY: ENC[AES256_GCM,data:JQsxcM9YOJOU0ybJt8cJ4hWhoZKrPaGoTs15bd7E04pgG7HO6qXG/g==,iv:01QKtO/ZtkBfnvtuemK+Fa85rESpruapkJPgtZANCDM=,tag:BdJ0rijVkYJNyoGKfwyhig==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1khwaa9sua4v5pdqp4jv42j88hh07dh0s8repl9s936xyueszjcqq0uexfu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuV1VZYTh0OXVQZi9DNGx1
            cy95M3d0TkpJZExaRDEwc0tidytsWEtleG5FClkrTE0zMTNQV3lRZjZ5TFRCUFZP
            c1lOQWVFd3lJSnRuQ2VuRmdKY2c4eFkKLS0tIDF1cUZtQldMM01SSFR6cm94YXRM
            aTUzVU0vMmttcjA2Ty9UcENSNm8wOHcKc09xHVSqy1CHPw95h3SA5RLJbP1+hrkL
            t9cdtNaLgk661yzYxoq7PXWAOd+gQE6ouNkQ6176r/Z/YRhDLkdXfg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-15T17:09:06Z"
    mac: ENC[AES256_GCM,data:uPQrjlhtzqeln+g6eluQGVUu70mlhzTgRnZwJLynwrkT04NvudWuASPWcKDNDwtcVHAu5PHTxvN3oCM64JXeObe28dn9vzp20BE5QaNxpG1TeDTBKGJV9ydl0o9VXTdSAReUzRvoZcaObYTgvOa3gN8otZlpffbuFKxKkcwbOr0=,iv:tg0glshoOlSP3/M3Tqi/VXASL3MKs37UDqmTh42Emow=,tag:e50Q7CTdeJbmaYEcHbuZfA==,type:str]
    pgp: []
    encrypted_regex: ^stringData
    version: 3.7.3
